In [5]:
import os
import glob
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer

In [6]:
#Declare the vectorizers
count_vectorizer=CountVectorizer(stop_words='english',max_features=100)
tfidf_vectorizer=TfidfVectorizer(stop_words='english',max_features=100)
hashing_vectorizer=HashingVectorizer(stop_words='english')

In [9]:
label_list=[]
text_list=[]
file_list=[]
fileDir="Section2-Chapter3"
df=pd.read_csv(fileDir+"/Labels.csv")

for row in df.itertuples(index=True, name='Pandas'):
    fileName=row.FileName+'.asm'
    with open("Section2-Chapter3/"+fileName, encoding='utf-8', errors='ignore') as f:
        content=f.read()
    content.replace(",", " ")
    content.replace('"', " ")
    text_list.append(content)
    file_list.append(fileName)
    label_list.append(row.Label)

In [10]:
#Create dataframe for Count Vectorizer
dtm=count_vectorizer.fit_transform(text_list)
df_count=pd.DataFrame(dtm.toarray(),columns=count_vectorizer.get_feature_names())
df_count['FileName']=pd.Series(file_list)
df_count['Label']=pd.Series(label_list)

In [ ]:
#Create dataframe for TF-IDF Vectorizer
dtm=tfidf_vectorizer.fit_transform(text_list)
df_tfidf=pd.DataFrame(dtm.toarray(),columns=tfidf_vectorizer.get_feature_names())
df_tfidf['FileName']=pd.Series(file_list)
df_tfidf['Label']=pd.Series(label_list)

In [11]:
df_count.head()

,00,01,02,03,04,06,07,08,09,0abh,...,nop,ptr,push,rdata,short,text,xref,zenc,FileName,Label
0,839,29,14,9,17,1,8,16,6,0,...,0,53,81,381,74,783,164,0,01kcPWA9K2BOxQeS5Rju.asm,1
1,21166,1332,766,584,1424,629,420,2027,171,2,...,43,4352,5927,0,2479,62737,5787,0,04EjIdbPV5e1XroFOpiN.asm,1
2,6289,339,168,65,379,82,55,482,68,0,...,0,610,915,4100,559,11161,1381,0,05EeG39MTRrI6VY21DPd.asm,1
3,55883,5437,2550,1973,4152,1577,2411,7577,881,2,...,157,15050,28620,0,11187,210924,17981,0,05rJTUWYAKNegBk2wE8X.asm,1
4,6777,607,148,244,468,102,121,426,60,0,...,4,564,781,801,1034,12928,1340,0,0AnoOZDNbPXIr2MRBSCJ.asm,1

In [131]:
df_tfidf.head()

,00,01,02,03,04,06,07,08,09,0abh,...,nop,ptr,push,rdata,short,text,xref,zenc,FileName,Label
0,0.647127,0.022368,0.010798,0.006942,0.013112,0.000771,0.006170,0.012341,0.004628,0.000000,...,0.000000,0.040879,0.062476,0.307078,0.057077,0.603934,0.126494,0.0,01kcPWA9K2BOxQeS5Rju.asm,1
1,0.295494,0.018596,0.010694,0.008153,0.019880,0.008781,0.005864,0.028298,0.002387,0.000040,...,0.000984,0.060757,0.082745,0.000000,0.034609,0.875857,0.080791,0.0,04EjIdbPV5e1XroFOpiN.asm,1
2,0.419026,0.022587,0.011194,0.004331,0.025252,0.005464,0.003665,0.032115,0.004531,0.000000,...,0.000000,0.040643,0.060965,0.285456,0.037245,0.743639,0.092014,0.0,05EeG39MTRrI6VY21DPd.asm,1
3,0.230619,0.022438,0.010523,0.008142,0.017135,0.006508,0.009950,0.031269,0.003636,0.000012,...,0.001062,0.062109,0.118110,0.000000,0.046167,0.870445,0.074204,0.0,05rJTUWYAKNegBk2wE8X.asm,1
4,0.408699,0.036606,0.008925,0.014715,0.028224,0.006151,0.007297,0.025691,0.003618,0.000000,...,0.000396,0.034013,0.047100,0.050477,0.062357,0.779646,0.080811,0.0,0AnoOZDNbPXIr2MRBSCJ.asm,1

In [12]:
#Feature Engneering section
df_count.to_csv('count_vectorizer.csv.zip', index=False,compression="zip") 
df_count=pd.read_csv("count_vectorizer.csv.zip")

In [ ]:

df_tfidf.to_csv('tfidf_vectorizer.csv.zip', index=False,compression="zip") 
df_tfidf=pd.read_csv("tfidf_vectorizer.csv.zip")

In [93]:
df_count.head()

,00,01,02,03,04,06,07,08,09,0abh,...,nop,ptr,push,rdata,short,text,xref,zenc,FileName,Label
0,839,29,14,9,17,1,8,16,6,0,...,0,53,81,381,74,783,164,0,01kcPWA9K2BOxQeS5Rju.asm,1
1,21166,1332,766,584,1424,629,420,2027,171,2,...,43,4352,5927,0,2479,62737,5787,0,04EjIdbPV5e1XroFOpiN.asm,1
2,6289,339,168,65,379,82,55,482,68,0,...,0,610,915,4100,559,11161,1381,0,05EeG39MTRrI6VY21DPd.asm,1
3,55883,5437,2550,1973,4152,1577,2411,7577,881,2,...,157,15050,28620,0,11187,210924,17981,0,05rJTUWYAKNegBk2wE8X.asm,1
4,6777,607,148,244,468,102,121,426,60,0,...,4,564,781,801,1034,12928,1340,0,0AnoOZDNbPXIr2MRBSCJ.asm,1

In [149]:
#Print Util Function
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, f1_score, recall_score
from prettytable import PrettyTable
def print_stats_metrices(algorithm_name, y_test, y_pred):
    x = PrettyTable()
    x.field_names = ["Algorithm", "Accuracy"]
    
    acc_score=accuracy_score(y_test, y_pred)
    x.add_row([algorithm_name,acc_score]);
    print(x)

In [94]:
Y=df_count['Label']
X = df_count.drop( columns=['FileName', 'Label'], axis=1)

In [133]:
Y1=df_tfidf['Label']
X1= df_tfidf.drop( columns=['FileName', 'Label'], axis=1)

In [163]:
#Normalizing the input and splitting train test data 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_normalized=StandardScaler().fit_transform(X)
X1_normalized=StandardScaler().fit_transform(X1)

X_Train, X_Test, Y_Train, Y_Test= train_test_split(X_normalized,Y,test_size=0.20, shuffle=True)

X1_Train, X1_Test, Y1_Train, Y1_Test= train_test_split(X1_normalized,Y,test_size=0.20, shuffle=True)

In [164]:
#CLassification using LogisticRegression
from sklearn.linear_model import LogisticRegression
#Logistic Regression

logReg1=LogisticRegression()
logReg1.fit(X_Train,Y_Train)
predictions=logReg1.predict(X_Test)

print_stats_metrices('LogisticRegression',Y_Test,predictions)

+--------------------+--------------------+
|     Algorithm      |      Accuracy      |
+--------------------+--------------------+
| LogisticRegression | 0.8888888888888888 |
+--------------------+--------------------+

In [165]:
#CLassification using LogisticRegression
from sklearn.linear_model import LogisticRegression
#Logistic Regression

logReg1=LogisticRegression()
logReg1.fit(X1_Train,Y1_Train)
predictions1=logReg1.predict(X1_Test)

print_stats_metrices('LogisticRegression',Y1_Test,predictions1)

+--------------------+--------------------+
|     Algorithm      |      Accuracy      |
+--------------------+--------------------+
| LogisticRegression | 0.9444444444444444 |
+--------------------+--------------------+